AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: JVM Template Lambda Functions
Parameters:
    Foo:
      Type: String
      Description: The url for the cerberus environment
Resources:
  JavaLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: >-
         com.fieldju.java.Handler::handle
      Runtime: java8
      Description: Java Lambda Function
      MemorySize: 512
      Timeout: 300
      CodeUri: @@LAMBDA_FAT_JAR@@
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          ROLE_NAME: !Ref LambdaRole
          ACCOUNT_ID: !Ref AWS::AccountId
          REGION: !Ref AWS::Region
  LambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "allow-lambda-to-use-logs-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
Outputs:
  HealthCheckEndpoint:
    Description: Role Arn
    Value: !GetAtt LambdaRole.Arn